#define DIR_TYPE models
#define INSTALL_TO models/char

#begin install_mat
  #define SOURCES \
    eyeball_l_medic.pmat \
    eyeball_r_medic.pmat

#end install_mat

#define MEDIC_ANIMS \
  AttackCrouch_PRIMARY \
  AttackCrouch_SECONDARY \
  AttackCrouch_SECONDARY_Postfire \
  AttackCrouch_SECONDARY_Prefire \
  AttackStand_PRIMARY \
  AttackStand_SECONDARY \
  AttackStand_SECONDARY_Prefire \
  AttackSwim_MELEE \
  AttackSwim_PRIMARY \
  AttackSwim_SECONDARY \
  MELEE_swing \
  Melee_Crouch_Swing \
  PRIMARY_Stun_begin \
  PRIMARY_placeSapper \
  PRIMARY_stun_end \
  PRIMARY_stun_middle \
  ReloadAirwalk_PRIMARY \
  ReloadCrouch_PRIMARY \
  ReloadStand_PRIMARY \
  ReloadSwim_PRIMARY \
  SelectionMenu_Anim01 \
  SelectionMenu_Idle \
  SelectionMenu_StartPose \
  a_AttackStandBase \
  a_MELEE_aimmatrix_crouch_idle_down_center \
  a_MELEE_aimmatrix_crouch_idle_down_left \
  a_MELEE_aimmatrix_crouch_idle_down_right \
  a_MELEE_aimmatrix_crouch_idle_mid_center \
  a_MELEE_aimmatrix_crouch_idle_mid_left \
  a_MELEE_aimmatrix_crouch_idle_mid_right \
  a_MELEE_aimmatrix_crouch_idle_neutral \
  a_MELEE_aimmatrix_crouch_idle_straight_up \
  a_MELEE_aimmatrix_crouch_idle_up_center \
  a_MELEE_aimmatrix_crouch_idle_up_left \
  a_MELEE_aimmatrix_crouch_idle_up_right \
  a_MELEE_aimmatrix_idle_down_center \
  a_MELEE_aimmatrix_idle_down_left \
  a_MELEE_aimmatrix_idle_down_right \
  a_MELEE_aimmatrix_idle_mid_center \
  a_MELEE_aimmatrix_idle_mid_left \
  a_MELEE_aimmatrix_idle_mid_right \
  a_MELEE_aimmatrix_idle_neutral \
  a_MELEE_aimmatrix_idle_straight_up \
  a_MELEE_aimmatrix_idle_up_center \
  a_MELEE_aimmatrix_idle_up_left \
  a_MELEE_aimmatrix_idle_up_right \
  a_MELEE_aimmatrix_run_down_center \
  a_MELEE_aimmatrix_run_down_left \
  a_MELEE_aimmatrix_run_down_right \
  a_MELEE_aimmatrix_run_mid_center \
  a_MELEE_aimmatrix_run_mid_left \
  a_MELEE_aimmatrix_run_mid_right \
  a_MELEE_aimmatrix_run_neutral \
  a_MELEE_aimmatrix_run_straight_up \
  a_MELEE_aimmatrix_run_up_center \
  a_MELEE_aimmatrix_run_up_left \
  a_MELEE_aimmatrix_run_up_right \
  a_Melee_Crouch_Swing \
  a_PRIMARY_aimmatrix_crouch_idle_down_center \
  a_PRIMARY_aimmatrix_crouch_idle_down_left \
  a_PRIMARY_aimmatrix_crouch_idle_down_right \
  a_PRIMARY_aimmatrix_crouch_idle_mid_center \
  a_PRIMARY_aimmatrix_crouch_idle_mid_left \
  a_PRIMARY_aimmatrix_crouch_idle_mid_right \
  a_PRIMARY_aimmatrix_crouch_idle_neutral \
  a_PRIMARY_aimmatrix_crouch_idle_straight_up \
  a_PRIMARY_aimmatrix_crouch_idle_up_center \
  a_PRIMARY_aimmatrix_crouch_idle_up_left \
  a_PRIMARY_aimmatrix_crouch_idle_up_right \
  a_PRIMARY_aimmatrix_idle_down_center \
  a_PRIMARY_aimmatrix_idle_down_left \
  a_PRIMARY_aimmatrix_idle_down_right \
  a_PRIMARY_aimmatrix_idle_mid_center \
  a_PRIMARY_aimmatrix_idle_mid_left \
  a_PRIMARY_aimmatrix_idle_mid_right \
  a_PRIMARY_aimmatrix_idle_neutral \
  a_PRIMARY_aimmatrix_idle_straight_up \
  a_PRIMARY_aimmatrix_idle_up_center \
  a_PRIMARY_aimmatrix_idle_up_left \
  a_PRIMARY_aimmatrix_idle_up_right \
  a_PRIMARY_aimmatrix_run_down_center \
  a_PRIMARY_aimmatrix_run_down_left \
  a_PRIMARY_aimmatrix_run_down_right \
  a_PRIMARY_aimmatrix_run_mid_center \
  a_PRIMARY_aimmatrix_run_mid_left \
  a_PRIMARY_aimmatrix_run_mid_right \
  a_PRIMARY_aimmatrix_run_neutral \
  a_PRIMARY_aimmatrix_run_straight_up \
  a_PRIMARY_aimmatrix_run_up_center \
  a_PRIMARY_aimmatrix_run_up_left \
  a_PRIMARY_aimmatrix_run_up_right \
  a_SECONDARY_aimmatrix_crouch_idle_down_center \
  a_SECONDARY_aimmatrix_crouch_idle_down_left \
  a_SECONDARY_aimmatrix_crouch_idle_down_right \
  a_SECONDARY_aimmatrix_crouch_idle_mid_center \
  a_SECONDARY_aimmatrix_crouch_idle_mid_left \
  a_SECONDARY_aimmatrix_crouch_idle_mid_right \
  a_SECONDARY_aimmatrix_crouch_idle_neutral \
  a_SECONDARY_aimmatrix_crouch_idle_straight_up \
  a_SECONDARY_aimmatrix_crouch_idle_up_center \
  a_SECONDARY_aimmatrix_crouch_idle_up_left \
  a_SECONDARY_aimmatrix_crouch_idle_up_right \
  a_SECONDARY_aimmatrix_crouch_walk_down_center \
  a_SECONDARY_aimmatrix_crouch_walk_down_left \
  a_SECONDARY_aimmatrix_crouch_walk_down_right \
  a_SECONDARY_aimmatrix_crouch_walk_mid_center \
  a_SECONDARY_aimmatrix_crouch_walk_mid_left \
  a_SECONDARY_aimmatrix_crouch_walk_mid_right \
  a_SECONDARY_aimmatrix_crouch_walk_neutral \
  a_SECONDARY_aimmatrix_crouch_walk_straight_up \
  a_SECONDARY_aimmatrix_crouch_walk_up_center \
  a_SECONDARY_aimmatrix_crouch_walk_up_left \
  a_SECONDARY_aimmatrix_crouch_walk_up_right \
  a_SECONDARY_aimmatrix_idle_down_center \
  a_SECONDARY_aimmatrix_idle_down_left \
  a_SECONDARY_aimmatrix_idle_down_right \
  a_SECONDARY_aimmatrix_idle_mid_center \
  a_SECONDARY_aimmatrix_idle_mid_left \
  a_SECONDARY_aimmatrix_idle_mid_right \
  a_SECONDARY_aimmatrix_idle_neutral \
  a_SECONDARY_aimmatrix_idle_straight_up \
  a_SECONDARY_aimmatrix_idle_up_center \
  a_SECONDARY_aimmatrix_idle_up_left \
  a_SECONDARY_aimmatrix_idle_up_right \
  a_SECONDARY_aimmatrix_run_down_center \
  a_SECONDARY_aimmatrix_run_down_left \
  a_SECONDARY_aimmatrix_run_down_right \
  a_SECONDARY_aimmatrix_run_mid_center \
  a_SECONDARY_aimmatrix_run_mid_left \
  a_SECONDARY_aimmatrix_run_mid_right \
  a_SECONDARY_aimmatrix_run_neutral \
  a_SECONDARY_aimmatrix_run_straight_up \
  a_SECONDARY_aimmatrix_run_up_center \
  a_SECONDARY_aimmatrix_run_up_left \
  a_SECONDARY_aimmatrix_run_up_right \
  a_blend_crouchN_crouch_walk_MELEE \
  a_blend_crouchN_crouch_walk_SECONDARY \
  a_crouch_walkCenter_PRIMARY \
  a_crouch_walkCenter_crouch_walk_MELEE \
  a_crouch_walkCenter_crouch_walk_SECONDARY \
  a_crouch_walkE_PRIMARY \
  a_crouch_walkE_crouch_walk_MELEE \
  a_crouch_walkE_crouch_walk_SECONDARY \
  a_crouch_walkNE_PRIMARY \
  a_crouch_walkNE_crouch_walk_MELEE \
  a_crouch_walkNE_crouch_walk_SECONDARY \
  a_crouch_walkNW_PRIMARY \
  a_crouch_walkNW_crouch_walk_MELEE \
  a_crouch_walkNW_crouch_walk_SECONDARY \
  a_crouch_walkN_PRIMARY \
  a_crouch_walkN_crouch_walk_MELEE \
  a_crouch_walkN_crouch_walk_SECONDARY \
  a_crouch_walkSE_PRIMARY \
  a_crouch_walkSE_crouch_walk_MELEE \
  a_crouch_walkSE_crouch_walk_SECONDARY \
  a_crouch_walkSW_PRIMARY \
  a_crouch_walkSW_crouch_walk_MELEE \
  a_crouch_walkSW_crouch_walk_SECONDARY \
  a_crouch_walkS_PRIMARY \
  a_crouch_walkS_crouch_walk_MELEE \
  a_crouch_walkS_crouch_walk_SECONDARY \
  a_crouch_walkW_PRIMARY \
  a_crouch_walkW_crouch_walk_MELEE \
  a_crouch_walkW_crouch_walk_SECONDARY \
  a_flinch01 \
  a_jumpfloat_E_LOSER \
  a_jumpfloat_E_MELEE \
  a_jumpfloat_E_PRIMARY \
  a_jumpfloat_E_SECONDARY \
  a_jumpfloat_LOSER \
  a_jumpfloat_MELEE \
  a_jumpfloat_NE_LOSER \
  a_jumpfloat_NE_MELEE \
  a_jumpfloat_NE_PRIMARY \
  a_jumpfloat_NE_SECONDARY \
  a_jumpfloat_NW_LOSER \
  a_jumpfloat_NW_MELEE \
  a_jumpfloat_NW_PRIMARY \
  a_jumpfloat_NW_SECONDARY \
  a_jumpfloat_N_LOSER \
  a_jumpfloat_N_MELEE \
  a_jumpfloat_N_PRIMARY \
  a_jumpfloat_N_SECONDARY \
  a_jumpfloat_PRIMARY \
  a_jumpfloat_SECONDARY \
  a_jumpfloat_SE_LOSER \
  a_jumpfloat_SE_MELEE \
  a_jumpfloat_SE_PRIMARY \
  a_jumpfloat_SE_SECONDARY \
  a_jumpfloat_SW_LOSER \
  a_jumpfloat_SW_MELEE \
  a_jumpfloat_SW_PRIMARY \
  a_jumpfloat_SW_SECONDARY \
  a_jumpfloat_S_LOSER \
  a_jumpfloat_S_MELEE \
  a_jumpfloat_S_PRIMARY \
  a_jumpfloat_S_SECONDARY \
  a_jumpfloat_W_LOSER \
  a_jumpfloat_W_MELEE \
  a_jumpfloat_W_PRIMARY \
  a_jumpfloat_W_SECONDARY \
  a_jumpstart_E_LOSER \
  a_jumpstart_E_MELEE \
  a_jumpstart_E_PRIMARY \
  a_jumpstart_E_SECONDARY \
  a_jumpstart_LOSER \
  a_jumpstart_MELEE \
  a_jumpstart_NE_LOSER \
  a_jumpstart_NE_MELEE \
  a_jumpstart_NE_PRIMARY \
  a_jumpstart_NE_SECONDARY \
  a_jumpstart_NW_LOSER \
  a_jumpstart_NW_MELEE \
  a_jumpstart_NW_PRIMARY \
  a_jumpstart_NW_SECONDARY \
  a_jumpstart_N_LOSER \
  a_jumpstart_N_MELEE \
  a_jumpstart_N_PRIMARY \
  a_jumpstart_N_SECONDARY \
  a_jumpstart_PRIMARY \
  a_jumpstart_SECONDARY \
  a_jumpstart_SE_LOSER \
  a_jumpstart_SE_MELEE \
  a_jumpstart_SE_PRIMARY \
  a_jumpstart_SE_SECONDARY \
  a_jumpstart_SW_LOSER \
  a_jumpstart_SW_MELEE \
  a_jumpstart_SW_PRIMARY \
  a_jumpstart_SW_SECONDARY \
  a_jumpstart_S_LOSER \
  a_jumpstart_S_MELEE \
  a_jumpstart_S_PRIMARY \
  a_jumpstart_S_SECONDARY \
  a_jumpstart_W_LOSER \
  a_jumpstart_W_MELEE \
  a_jumpstart_W_PRIMARY \
  a_jumpstart_W_SECONDARY \
  a_reference \
  a_runCenter_LOSER \
  a_runCenter_MELEE \
  a_runCenter_PRIMARY \
  a_runCenter_SECONDARY \
  a_runE_LOSER \
  a_runE_MELEE \
  a_runE_PRIMARY \
  a_runE_SECONDARY \
  a_runNE_LOSER \
  a_runNE_MELEE \
  a_runNE_PRIMARY \
  a_runNE_SECONDARY \
  a_runNW_LOSER \
  a_runNW_MELEE \
  a_runNW_PRIMARY \
  a_runNW_SECONDARY \
  a_runN_LOSER \
  a_runN_MELEE \
  a_runN_PRIMARY \
  a_runN_SECONDARY \
  a_runSE_LOSER \
  a_runSE_MELEE \
  a_runSE_PRIMARY \
  a_runSE_SECONDARY \
  a_runSW_LOSER \
  a_runSW_MELEE \
  a_runSW_PRIMARY \
  a_runSW_SECONDARY \
  a_runS_LOSER \
  a_runS_MELEE \
  a_runS_PRIMARY \
  a_runS_SECONDARY \
  a_runW_LOSER \
  a_runW_MELEE \
  a_runW_PRIMARY \
  a_runW_SECONDARY \
  a_stun_endpose \
  a_stun_startpose \
  a_swimCenter_LOSER \
  a_swimCenter_MELEE \
  a_swimCenter_PRIMARY \
  a_swimCenter_SECONDARY \
  a_swimE_LOSER \
  a_swimE_MELEE \
  a_swimE_PRIMARY \
  a_swimE_SECONDARY \
  a_swimNE_LOSER \
  a_swimNE_MELEE \
  a_swimNE_PRIMARY \
  a_swimNE_SECONDARY \
  a_swimNW_LOSER \
  a_swimNW_MELEE \
  a_swimNW_PRIMARY \
  a_swimNW_SECONDARY \
  a_swimN_LOSER \
  a_swimN_MELEE \
  a_swimN_PRIMARY \
  a_swimN_SECONDARY \
  a_swimSE_LOSER \
  a_swimSE_MELEE \
  a_swimSE_PRIMARY \
  a_swimSE_SECONDARY \
  a_swimSW_LOSER \
  a_swimSW_MELEE \
  a_swimSW_PRIMARY \
  a_swimSW_SECONDARY \
  a_swimS_LOSER \
  a_swimS_MELEE \
  a_swimS_PRIMARY \
  a_swimS_SECONDARY \
  a_swimW_LOSER \
  a_swimW_MELEE \
  a_swimW_PRIMARY \
  a_swimW_SECONDARY \
  arm_pose_01 \
  armslayer_melee_Crouch_swing \
  bodylayer_Melee_Crouch_Swing \
  crouch_LOSER \
  crouch_MELEE \
  crouch_PRIMARY \
  crouch_SECONDARY \
  dieviolent \
  gesture_melee_cheer \
  gesture_melee_go \
  gesture_melee_help \
  gesture_melee_positive \
  gesture_primary_cheer \
  gesture_primary_go \
  gesture_primary_help \
  gesture_primary_positive \
  gesture_secondary_cheer \
  gesture_secondary_go \
  gesture_secondary_help \
  gesture_secondary_positive \
  hand_pose_01 \
  hand_pose_02 \
  jump_MELEE \
  jumpland_LOSER \
  jumpland_MELEE \
  jumpland_PRIMARY \
  jumpland_SECONDARY \
  layerBlend_attackSwimMelee_S_arms \
  layer_AttackStandMelee_arms \
  layer_AttackStandMelee_runW_arms \
  layer_AttackStand_SECONDARY_Postfire \
  layer_AttackSwimMelee_S_arms \
  layer_PRIMARY_Stun_begin \
  layer_PRIMARY_Stun_end \
  layer_PRIMARY_jump_floatNoise \
  layer_PRIMARY_stun_middle \
  layer_airwalkXtraNoise \
  layer_dieviolent \
  layer_gesture_melee_cheer_armL \
  layer_gesture_melee_go_armL \
  layer_gesture_melee_help_armL \
  layer_gesture_melee_positive_armL \
  layer_gesture_primary_cheer_armL \
  layer_gesture_primary_go_armL \
  layer_gesture_primary_help_armL \
  layer_gesture_primary_positive_armL \
  layer_gesture_secondary_cheer_armR \
  layer_gesture_secondary_go_armR \
  layer_gesture_secondary_help_armR \
  layer_gesture_secondary_positive_armR \
  layer_idleNoise \
  layer_melee_swing \
  layer_melee_swing_runW \
  layer_placeSapper_ArmL \
  layer_reload_standing_arms_primary \
  layer_taunt01 \
  layer_taunt02 \
  layer_taunt03 \
  layer_taunt06 \
  layer_taunt08 \
  layer_taunt09 \
  primary_death_backstab \
  primary_death_burning \
  primary_death_headshot \
  r_handposes \
  ragdollspawn \
  saxxy_pose \
  stand_LOSER \
  stand_MELEE \
  stand_PRIMARY \
  stand_SECONDARY \
  taunt01 \
  taunt02 \
  taunt03 \
  taunt06 \
  taunt07 \
  taunt08 \
  taunt09

#define MEDIC_OPTCHAR_OPTS \
  -keepall \
  -flag medic_morphs_low,medic_morphs_low_lod1 \
  -flag medic_morphs_low_lod2,medic_morphs_low_lod3 \
  -flag medic_morphs_low_lod4,medic_morphs_low_lod5 \
  -flag medic_physics

#call tf_char_egg medic,$[MEDIC_ANIMS],$[MEDIC_OPTCHAR_OPTS]

#begin install_mdl
  #define SOURCES \
    medic.pmdl
#end install_mdl
