#define DIR_TYPE models
#define INSTALL_TO models/props_mining

#include $[THISDIRPREFIX]Sources.barbfence001_reference.pp
#include $[THISDIRPREFIX]Sources.fence001_reference.pp
#include $[THISDIRPREFIX]Sources.industrial_ceiling_lamp.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor512.pp
#include $[THISDIRPREFIX]Sources.conveyor_belt.pp
#include $[THISDIRPREFIX]Sources.wooden_rail01.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_64.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe04.pp
#include $[THISDIRPREFIX]Sources.industrial_ceiling_lamp02.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_16_up.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe04_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_256_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_64_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_16_up_thick.pp
#include $[THISDIRPREFIX]Sources.fence003_reference.pp
#include $[THISDIRPREFIX]Sources.barbfence002_reference.pp
#include $[THISDIRPREFIX]Sources.crane002.pp
#include $[THISDIRPREFIX]Sources.cranehook001.pp
#include $[THISDIRPREFIX]Sources.board002_reference.pp
#include $[THISDIRPREFIX]Sources.board001_reference.pp
#include $[THISDIRPREFIX]Sources.sign001.pp
#include $[THISDIRPREFIX]Sources.factory_pipe004.pp
#include $[THISDIRPREFIX]Sources.factory_hatch001.pp
#include $[THISDIRPREFIX]Sources.computer_industrial02.pp
#include $[THISDIRPREFIX]Sources.computer_industrial05.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe03.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe01.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06_thin.pp
#include $[THISDIRPREFIX]Sources.crank01.pp
#include $[THISDIRPREFIX]Sources.crank02.pp
#include $[THISDIRPREFIX]Sources.computer_industrial03.pp
#include $[THISDIRPREFIX]Sources.computer_industrial01.pp
#include $[THISDIRPREFIX]Sources.computer_industrial04.pp
#include $[THISDIRPREFIX]Sources.barbedfence_set01.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor384.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe05.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02.pp
#include $[THISDIRPREFIX]Sources.junctionbox03.pp
#include $[THISDIRPREFIX]Sources.junctionbox02.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe01_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe05_thick.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor256.pp
