#define DIR_TYPE models
#define INSTALL_TO models/props_mining

#include $[THISDIRPREFIX]Sources.barbfence001_reference.pp
#include $[THISDIRPREFIX]Sources.fence001_reference.pp
#include $[THISDIRPREFIX]Sources.industrial_ceiling_lamp.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor512.pp
#include $[THISDIRPREFIX]Sources.conveyor_belt.pp
#include $[THISDIRPREFIX]Sources.wooden_rail01.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_64.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe04.pp
#include $[THISDIRPREFIX]Sources.industrial_ceiling_lamp02.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_16_up.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe04_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_256_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_64_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_16_up_thick.pp
#include $[THISDIRPREFIX]Sources.fence003_reference.pp
#include $[THISDIRPREFIX]Sources.barbfence002_reference.pp
#include $[THISDIRPREFIX]Sources.crane002.pp
#include $[THISDIRPREFIX]Sources.cranehook001.pp
#include $[THISDIRPREFIX]Sources.board002_reference.pp
#include $[THISDIRPREFIX]Sources.board001_reference.pp
#include $[THISDIRPREFIX]Sources.sign001.pp
#include $[THISDIRPREFIX]Sources.factory_pipe004.pp
#include $[THISDIRPREFIX]Sources.factory_hatch001.pp
#include $[THISDIRPREFIX]Sources.computer_industrial02.pp
#include $[THISDIRPREFIX]Sources.computer_industrial05.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe03.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe01.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06_thin.pp
#include $[THISDIRPREFIX]Sources.crank01.pp
#include $[THISDIRPREFIX]Sources.crank02.pp
#include $[THISDIRPREFIX]Sources.computer_industrial03.pp
#include $[THISDIRPREFIX]Sources.computer_industrial01.pp
#include $[THISDIRPREFIX]Sources.computer_industrial04.pp
#include $[THISDIRPREFIX]Sources.barbedfence_set01.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor384.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe05.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02.pp
#include $[THISDIRPREFIX]Sources.junctionbox03.pp
#include $[THISDIRPREFIX]Sources.junctionbox02.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe01_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe05_thick.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor256.pp
#include $[THISDIRPREFIX]Sources.mining_shack001a.pp
#include $[THISDIRPREFIX]Sources.factory_pipe001.pp
#include $[THISDIRPREFIX]Sources.billboard001.pp
#include $[THISDIRPREFIX]Sources.rock006c.pp
#include $[THISDIRPREFIX]Sources.track_straight_256.pp
#include $[THISDIRPREFIX]Sources.track_arc_90degree_128.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_c_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_256_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_l_160_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_128_01.pp
#include $[THISDIRPREFIX]Sources.generator01.pp
#include $[THISDIRPREFIX]Sources.generator_pipe01.pp
#include $[THISDIRPREFIX]Sources.junctionbox01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_l_128_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_corner128_01.pp
#include $[THISDIRPREFIX]Sources.factory_pipe005.pp
#include $[THISDIRPREFIX]Sources.truss004.pp
#include $[THISDIRPREFIX]Sources.truss006.pp
#include $[THISDIRPREFIX]Sources.dustbowl_roof03.pp
#include $[THISDIRPREFIX]Sources.truss001_256.pp
#include $[THISDIRPREFIX]Sources.crane001.pp
#include $[THISDIRPREFIX]Sources.support_wall001a.pp
#include $[THISDIRPREFIX]Sources.silo_top001.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss03c.pp
#include $[THISDIRPREFIX]Sources.track_straight_128.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_48.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_96.pp
#include $[THISDIRPREFIX]Sources.track_arc_90degree_256.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_96_mirrored.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_48_mirrored.pp
#include $[THISDIRPREFIX]Sources.minehead.pp
#include $[THISDIRPREFIX]Sources.watertower.pp
#include $[THISDIRPREFIX]Sources.track_y_joint_s_curve_96.pp
#include $[THISDIRPREFIX]Sources.rock003.pp
#include $[THISDIRPREFIX]Sources.rock002.pp
#include $[THISDIRPREFIX]Sources.rock001.pp
#include $[THISDIRPREFIX]Sources.rock004.pp
#include $[THISDIRPREFIX]Sources.rock005.pp
#include $[THISDIRPREFIX]Sources.rock006.pp
#include $[THISDIRPREFIX]Sources.quarry_rock02.pp
#include $[THISDIRPREFIX]Sources.rock006b.pp
#include $[THISDIRPREFIX]Sources.wooden_barrier01.pp
#include $[THISDIRPREFIX]Sources.factory_pipe003.pp
#include $[THISDIRPREFIX]Sources.truss001b_256.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128_thin.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02_thin.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe03_thin.pp
#include $[THISDIRPREFIX]Sources.factory_pipe002.pp
#include $[THISDIRPREFIX]Sources.truss005b.pp
#include $[THISDIRPREFIX]Sources.truss005.pp
#include $[THISDIRPREFIX]Sources.mining_scaffolding01.pp
#include $[THISDIRPREFIX]Sources.bridge_support01.pp
#include $[THISDIRPREFIX]Sources.crane003.pp
#include $[THISDIRPREFIX]Sources.support_cluster001a.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss01.pp
#include $[THISDIRPREFIX]Sources.rafter_cluster001a.pp
#include $[THISDIRPREFIX]Sources.truss009.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss02.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss03d.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss03b.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss03a.pp
#include $[THISDIRPREFIX]Sources.truss008.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss03e.pp
#include $[THISDIRPREFIX]Sources.billboard_skybox001.pp
#include $[THISDIRPREFIX]Sources.rock003_skybox.pp
#include $[THISDIRPREFIX]Sources.dustbowl_roof02.pp
#include $[THISDIRPREFIX]Sources.dustbowl_roof01.pp
#include $[THISDIRPREFIX]Sources.track_straight_64.pp
#include $[THISDIRPREFIX]Sources.rock007.pp
#include $[THISDIRPREFIX]Sources.rock005_skybox.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_s_01.pp
#include $[THISDIRPREFIX]Sources.track_y_joint_arc_90.pp
#include $[THISDIRPREFIX]Sources.crane001_small.pp
#include $[THISDIRPREFIX]Sources.tunnel_truss01b.pp
